# This is a basic workflow to help you get started with Actions

name: Recipe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development", "staging", "main" ]
  pull_request:
    branches: [ "development", "staging", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greet:
    name: "ðŸ‘´ðŸ‘µ Welcome customer"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to whoever is reading this
        run: |
          echo "### Welcome to Workflow Pizzeria! :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "Here's what we need to do:" >> $GITHUB_STEP_SUMMARY
          echo "- Make dough" >> $GITHUB_STEP_SUMMARY
          echo "- Make sauce" >> $GITHUB_STEP_SUMMARY
          echo "- Make toppings" >> $GITHUB_STEP_SUMMARY
          echo "- Assemble and bake" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Ready? Good thing we have staff in this pizzeria... Okay it's just me and my wife." >> $GITHUB_STEP_SUMMARY

  dough:
    name: "ðŸ‘µ Make dough"
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Make dough
        run: |
          echo "### Dough :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "Flour, water, yeast, oil, mix and knead. And also let it proof!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Today's crust is going to be... a secret!" >> $GITHUB_STEP_SUMMARY

  toppings:
    name: "ðŸ‘´ Make toppings"
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Make toppings
        run: |
          echo "### Toppings :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "We actually have a secret topping, let me get it. Maybe it'll be polarising." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Today's topping is going to be... a surprise!" >> $GITHUB_STEP_SUMMARY

  proof-dough:
    name: "ðŸ‘µ Proof dough"
    needs: dough
    runs-on: ubuntu-latest
    steps:
      - name: Proof dough
        run: |
          echo "### Proof dough :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "It's not ready to eat just yet! You don't trust me?" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Look, I have proof!" >> $GITHUB_STEP_SUMMARY

  sauce:
    name: "ðŸ‘µ Make sauce"
    needs: proof-dough
    runs-on: ubuntu-latest
    steps:
      - name: Make sauce
        run: |
          echo "### Sauce :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "Our sauce? You came here for our sauce? I can tell you where I buy it!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Today's sauce is going to be... wouldn't you like to know!" >> $GITHUB_STEP_SUMMARY

  pat-dog:
    name: "ðŸ‘µ Pat dog"
    needs: sauce
    runs-on: ubuntu-latest
    steps:
      - name: Pat dog
        run: |
          echo "### Have you met Gelato? :dog:" >> $GITHUB_STEP_SUMMARY

  charge-customer:
    name: "ðŸ‘µ Charge customer"
    needs: pat-dog
    runs-on: ubuntu-latest
    steps:
      - name: Charge customer
        run: |
          echo "### At the till :receipt:" >> $GITHUB_STEP_SUMMARY
          echo "While that's going on, here's your receipt!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "No we don't accept Bitcoin here sorry." >> $GITHUB_STEP_SUMMARY

  gather-wood:
    name: "ðŸ‘´ Get wood from out back"
    needs: [dough, toppings]
    runs-on: ubuntu-latest
    steps:
      - name: Get wood from out back
        run: |
          echo "### Almost fire time :wood:" >> $GITHUB_STEP_SUMMARY
          echo "Oh no wait, let me get some wood for this oven." >> $GITHUB_STEP_SUMMARY

  preheat:
    name: "ðŸ‘´ Get oven to temp"
    needs: gather-wood
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Preheat oven
        run: |
          echo "### Oven Temp :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "We need our ol' trusty wood-fired oven to be hot hot hot!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Should be ready soon..." >> $GITHUB_STEP_SUMMARY

  cook:
    name: "ðŸ‘´ Cook!"
    needs: preheat
    runs-on: ubuntu-latest

    environment: development

    steps:
      - uses: actions/checkout@v2
      - name: Cook the pizza
        run: |
          echo "### Cook :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "We did it! Now we just have to wait for this pie to come out." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Here it is! Your beautiful pizza consists of:" >> $GITHUB_STEP_SUMMARY
          echo "# ***REDACTED***" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ secrets.CRUST }} crust" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ secrets.SAUCE }} sauce" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ secrets.TOPPINGS }} for toppings" >> $GITHUB_STEP_SUMMARY
      
      - name: Create pizza
        run: |
          echo "##### ${{ secrets.CRUST }}> " > pizza.md

  farewell:
    name: "ðŸ‘´ðŸ‘µðŸ¶ Farewell!"
    needs: [cook, charge-customer]
    runs-on: ubuntu-latest

    steps:
      - name: Farewell the customer
        run: |
          echo "### Thanks for coming! :pizza:" >> $GITHUB_STEP_SUMMARY
          echo "${{ secrets.CRUST }} crust"
          echo "${{ secrets.SAUCE }} sauce"
          echo "${{ secrets.TOPPINGS }} for toppings"